# Generated by Django 5.1.2 on 2024-10-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Катерогии',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Перевозка Мебели')),
                ('Company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('experience', models.CharField(default='без опыта', max_length=85, verbose_name='Стаж работы')),
                ('Salary', models.CharField(max_length=85, verbose_name='Оклад')),
                ('Description', models.TextField(verbose_name='Описание предложения')),
                ('Skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('Address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('Phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('Mail', models.CharField(max_length=100, verbose_name='E-mail')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asian_app.category', verbose_name='Выберите категории')),
            ],
            options={
                'verbose_name': 'Вакансии',
            },
        ),
    ]
