# Generated by Django 5.1.2 on 2024-10-26 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asian_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Предложении'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='Title',
        ),
        migrations.AddField(
            model_name='job',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Актуальные предложения'),
            preserve_default=False,
        ),
    ]
