# Generated by Django 5.1.2 on 2024-10-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asian_app', '0002_alter_category_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Информации')),
                ('description', models.TextField(verbose_name='Описание информации')),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Информации',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Skills',
            new_name='skills',
        ),
    ]
