# Generated by Django 5.1.2 on 2024-10-29 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asian_app', '0003_information_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Избранное')),
                ('created_id', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Избранные',
            },
        ),
    ]
